<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <BaseOutputPath>$(MSBuildThisFileDirectory)out\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)out\obj\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ILGPU" Version="*" />
    <PackageReference Include="ILGPU.Algorithms" Version="*" />
    <PackageReference Include="ComputeSharp" Version="*" />
  </ItemGroup>
</Project>
